CREATE TABLE Cliente (
    id SERIAL PRIMARY KEY,
    nome_cliente VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(100) NOT NULL,
    telefone VARCHAR(20),
    ativo BOOLEAN DEFAULT TRUE,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Pessoa_Fisica (
    id INTEGER PRIMARY KEY REFERENCES Cliente(id),
    cpf CHARACTER(11) UNIQUE NOT NULL
);

CREATE TABLE Pessoa_Juridica (
    id INTEGER PRIMARY KEY REFERENCES Cliente(id),
    cnpj CHARACTER(14) UNIQUE NOT NULL,
    razao_social VARCHAR(150)
);